version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ec2-user/deployment
permissions:
  - object: /var/www/ec2-user/deployment
    owner: ec2-user
    group: ec2-user
    pattern: "*"
    mode: 775
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deployment_scripts/arrange-deployment-folders.sh
      runas: root
  AfterInstall:
    - location: deployment_scripts/db-config.sh
      runas: nginx
    - location: deployment_scripts/install-gems.sh
      runas: nginx
    - location: deployment_scripts/compile-assets.sh
      runas: nginx
    - location: deployment_scripts/run-db-migrations.sh
      runas: nginx

  ApplicationStart:
    - location: deployment_scripts/finish-installation.sh
      runas: root
