version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ec2-user/deployment
permissions:
  - object: /var/www/ec2-user/deployment
    mode: 644
    acls:
      - "d:u::rwx"
      - "d:g::rwx"
      - "d:o::rwx"
    owner: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: deployment_scripts/arrange-deployment-folders.sh
      runas: root
  AfterInstall:
    - location: deployment_scripts/db-config.sh
      runas: nginx
    - location: deployment_scripts/install-gems.sh
      runas: nginx
    - location: deployment_scripts/compile-assets.sh
      runas: nginx
    - location: deployment_scripts/run-db-migrations.sh
      runas: nginx

  ApplicationStart:
    - location: deployment_scripts/finish-installation.sh
      runas: root
