version: "2.0"

services:
  mysql:
    image: mysql:5.6.34
    restart: always
    volumes_from:
      - dbdata
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: RangeSharingReactRubyAPI_production

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql

  app:
    build: .
    environment:
      RAILS_ENV: production
      PASSENGER_APP_ENV: production
      DB_USER: root
      DB_NAME: RangeSharingReactRubyAPI_production
      DB_PASSWORD: dev
      DB_HOST: mysql
    volumes_from:
      - appdata
    links:
      - mysql

  appdata:
    image: tianon/true
    volumes:
      - "./:/workspace"
