branch-defaults:
  master:
    environment: production
environment-defaults:
  Secondpokerapp-env:
    branch: master
    repository: LighsailDeploy
global:
  application_name: SecondPokerApp
  branch: null
  default_ec2_keyname: NewestAWSKeyPair
  default_platform: Passenger with Ruby 2.6 running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
