#!/bin/bash

cd /home/ec2-user
yum update -y

# Installing ruby version 2.7
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | sudo bash -s stable
usermod -a -G rvm `whoami`
rvm install ruby-2.7.1
rvm --default use ruby-2.7.1
gem install bundler --no-rdoc --no-ri

#install node for rails 

apt-get install -y nodejs && ln -sf /usr/bin/nodejs /usr/local/bin/node

apt-get install -y dirmngr gnupg apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7 apt-get install -y apt-transport-https ca-certificates

sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list' apt-get update

apt-get install -y libnginx-mod-http-passenger

if [ ! -f /etc/nginx/modules-enabled/50-mod-http-passenger.conf ]; then sudo ln -s /usr/share/nginx/modules-available/mod-http-passenger.load /etc/nginx/modules-enabled/50-mod-http-passenger.conf ; fi ls /etc/nginx/conf.d/mod-http-passenger.conf

service nginx restart
/usr/bin/passenger-config validate-install