#!/bin/bash

cd /home/ec2-user
yum update -y

# Installing ruby version 2.7
yum install ruby27 -y
# Installing ruby development kit (needed to build gems)
yum install ruby27-devel.x86_64 -y
# Installing c++ garbage collector (needed to build gems)
yum install gcc-c++ -y
# Setting ruby version 2.7 as default
alternatives --set ruby /usr/bin/ruby2.7
gem2.7 install bundler --bindir /usr/bin