#!/bin/bash

cd /home/ec2-user
yum update -y

# Installing ruby version 2.7
sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | sudo bash -s stable
sudo usermod -a -G rvm `whoami`
rvm install ruby-2.7.1
rvm --default use ruby-2.7.1