/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:844a053d-2b39-4049-b0fa-6adbf8db5363",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_gc58ksVOc",
  aws_user_pools_web_client_id: "7m6e2g1faj08csgit1fn81ln35",
  oauth: {},
  aws_user_files_s3_bucket: "dbpokerappstorage233501-dev",
  aws_user_files_s3_bucket_region: "us-east-2",
  aws_content_delivery_bucket:
    "angeharingeactub-20200528204718-hostingbucket-dev",
  aws_content_delivery_bucket_region: "us-east-2",
  aws_content_delivery_url:
    "http://angeharingeactub-20200528204718-hostingbucket-dev.s3-website.us-east-2.amazonaws.com"
};

export default awsmobile;
